apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-backend
  namespace: ticket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-backend
  template:
    metadata:
      labels:
        app: ticket-backend
    spec:
      containers:
        - name: backend
          image: ticket-backend:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ticket-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: POSTGRES_PASSWORD
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: JWT_SECRET
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: MAIL_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
